### PR TITLE
Fix Last Modified value for website pages

### PR DESCRIPTION
**Pull request by aLekSer**
Currently https://open-match.dev/site/docs/ contains `Last modified January 1, 0001`.

See for more details:
https://gohugo.io/getting-started/configuration/#configure-dates

### CODE REVIEW

**Comment by aLekSer** [comment]
It seems that this solution does not work in Cloud Build:
```
Building sites … ERROR 2020/05/28 18:32:08 Failed to read Git log: fatal: not a git repository (or any parent up to mount point /)
```

**Comment by Laremere** [comment]
Thanks for noticing this issue.  I would be happy with either this working (if you can get it to work with cloud build), or the last updated being removed.

**Comment by aLekSer** [comment]
Now the date is more accurate it would be received from the file modification date.

**Comment by Laremere** [comment]
Is `Last modified July 31, 2020`  right?
Is it taking the time the file was created from the git operations, instead of when it was modified in git?

**Comment by aLekSer** [comment]
>Is Last modified July 31, 2020 right?
It takes file modification date and all pages throughout website would be the same and have marked with the deployment date.
This fix is in the middle between removing this date completely and adding `.git` directory into build process, which is harder to solve at the moment (we have `.gcloudignore` on `.git` dir and we are copying the whole website directory into a new place):
https://github.com/googleforgames/open-match-docs/blob/9f21ff08cb210ce925c8bcb3983aee52c27688dc/Makefile#L213

**Comment by Laremere** [comment]
Thanks for the changes.

**Pull request merged**
